#!/usr/bin/env bash
# Copyright(c) The Maintainers of Nanvix.
# Licensed under the MIT License.
#
# Cross-compile wordcloud C extension for Nanvix (i686).
# wordcloud has a single C file (query_integral_image.c) generated by Cython.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DIST_DIR="$SCRIPT_DIR/dist"

TOOLCHAIN="${NANVIX_TOOLCHAIN:-/opt/nanvix}"
CC="${TOOLCHAIN}/bin/i686-nanvix-gcc"
AR="${TOOLCHAIN}/bin/i686-nanvix-ar"

CPYTHON_HEADERS="$SCRIPT_DIR/cpython-headers/python3.12"

CFLAGS="-O2 -fPIC -DNDEBUG"
CFLAGS="$CFLAGS -I${CPYTHON_HEADERS}"
CFLAGS="$CFLAGS -I${REPO_ROOT}/wordcloud"

mkdir -p "$DIST_DIR/obj"

echo "[wordcloud] Cross-compiling C extension for i686-nanvix..."

SRC="$REPO_ROOT/wordcloud/query_integral_image.c"
if [ ! -f "$SRC" ]; then
    echo "[wordcloud] Generating Cython source..."
    cd "$REPO_ROOT"
    cython wordcloud/query_integral_image.pyx || {
        echo "ERROR: cython not found and .c file missing"; exit 1
    }
fi

$CC $CFLAGS -c "$SRC" -o "$DIST_DIR/obj/query_integral_image.o"

echo "[wordcloud] Creating static archive..."
$AR rcs "$DIST_DIR/libwordcloud.a" "$DIST_DIR/obj/query_integral_image.o"

echo "[wordcloud] Done: $DIST_DIR/libwordcloud.a"
ls -la "$DIST_DIR/libwordcloud.a"
